http:
  routers:
    server:
      rule: "Host(`server.localhost`) || Host(`localhost`) || HostRegexp(`^\\d+\\.\\d+\\.\\d+\\.\\d+$`)"
      entryPoints:
        - web
      service: server
      priority: 1

    casdoor:
      rule: "Host(`oauth.localhost`)"
      entryPoints:
        - web
      service: casdoor

    web:
      rule: "Host(`app.localhost`)"
      entryPoints:
        - web
      service: web

    dashboard:
      rule: "Host(`traefik.localhost`)"
      entryPoints:
        - web
      service: api@internal

  services:
    server:
      loadBalancer:
        servers:
          - url: "http://server:8080"

    casdoor:
      loadBalancer:
        servers:
          - url: "http://casdoor:8000"

    web:
      loadBalancer:
        servers:
          - url: "http://web:80"
