name: cat_calories_server
description: Standalone Cat Calories sync server.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cat_calories_core:
    path: ../core
  sqlite3: ^2.7.0
  http: ^1.2.2
  uuid: ^4.5.1
  crypto: ^3.0.6
