/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all calorie records for the current profile */
        get: operations["listRecords"];
        put?: never;
        /** Create a new calorie record */
        post: operations["createRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a calorie record */
        put: operations["updateRecord"];
        post?: never;
        /** Delete a calorie record */
        delete: operations["deleteRecord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get home dashboard with calorie stats */
        get: operations["getHomeDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CalorieRecord: {
            id: string;
            /** Format: double */
            value: number;
            description: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            eaten_at: string | null;
            /** Format: double */
            weight_grams: number | null;
            /** Format: double */
            protein_grams: number | null;
            /** Format: double */
            fat_grams: number | null;
            /** Format: double */
            carb_grams: number | null;
        };
        Profile: {
            name: string;
            calories_limit_goal: number;
        };
        RecentMeal: {
            id: string;
            /** Format: double */
            value: number;
            description: string | null;
            /** Format: date-time */
            eaten_at: string;
        };
        PeriodSummary: {
            /** Format: double */
            calories: number;
            /** Format: double */
            goal: number;
        };
        RecordsResponse: {
            profile: components["schemas"]["Profile"];
            records: components["schemas"]["CalorieRecord"][];
        };
        SingleRecordResponse: {
            record: components["schemas"]["CalorieRecord"];
        };
        CreateRecordRequest: {
            /** Format: double */
            value: number;
            description?: string | null;
            /** Format: date-time */
            eaten_at?: string | null;
            /** Format: double */
            weight_grams?: number | null;
            /** Format: double */
            protein_grams?: number | null;
            /** Format: double */
            fat_grams?: number | null;
            /** Format: double */
            carb_grams?: number | null;
        };
        UpdateRecordRequest: {
            /** Format: double */
            value?: number;
            description?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            eaten_at?: string | null;
            /** Format: double */
            weight_grams?: number | null;
            /** Format: double */
            protein_grams?: number | null;
            /** Format: double */
            fat_grams?: number | null;
            /** Format: double */
            carb_grams?: number | null;
        };
        DeleteResponse: {
            deleted: boolean;
        };
        HomeDashboardResponse: {
            profile: components["schemas"]["Profile"];
            /** Format: double */
            rolling_24h: number;
            /** Format: double */
            today: number;
            /** Format: double */
            yesterday: number;
            /** Format: double */
            avg_7_days: number;
            period: components["schemas"]["PeriodSummary"] | null;
            recent_meals: components["schemas"]["RecentMeal"][];
        };
        ErrorResponse: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Records list with profile info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createRecord: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecordRequest"];
            };
        };
        responses: {
            /** @description Created record */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleRecordResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRecordRequest"];
            };
        };
        responses: {
            /** @description Updated record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleRecordResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHomeDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeDashboardResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
